config/routes.rb
Rails.application.routes.draw do

  resources :movies do 
    resources :reviews, only: [:show, :create, :destroy]
    resources :cast_members, only: [:show, :create, :destroy]
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

   root 'movies#index'

end

app/models/cast_member.rb
class CastMember < ActiveRecord::Base
  has_many :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates :title, :release_year, presence: true
  validates :duration, numericality: {only_integer: true}

  has_many :reviews
  has_many :users, through: :reviews
  has_many :cast_members 


  def formatted_duration
    time_in_hours = duration.to_f / 60.0
    sprintf("%.2f", time_in_hours)  
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews
  has_many :movies, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_filter: check_country 

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    true
  end
end

app/controllers/cast_members_controller.rb
class CastMembersController < ApplicationController
  before_filter :load_movie
  before_filter :ensure_logged_in, only: [:create, :destroy]

  def show
    @cast_member = CastMember.find(params[:id])
  end

  def create
    @cast_member = @movie.cast_members.build(cast_member_params)
    

    if @cast_member.save
      redirect_to movies_path, notice: 'Cast Member Saved!'
    else
      render 'movies/show'
    end
  end

  def destroy
    @cast_member = CastMember.find(params[:id])
    @cast_member.destroy
  end

  private
  def cast_member_params
    params.require(:cast_member).permit(:name, :role, :movie_id)
  end

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_filter :load_movie, only: [:show, :edit, :update, :destroy] 
  # before_filter :load_movie, :except => [:index, :new, :create] 
  # before_filter :ensure_logged_in 

  # skip_before_filter :check_country, :except =>index 
 # before_action  same as before_filter

  def index
    @movies = Movie.all    
  end

  def show   
      if current_user
      @review = @movie.reviews.build 
      @cast_member = @movie.cast_members.build 
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path # browser is going to make a new get request for '/movies'; issue the action
    else
      render :new # render will not issue a request to the server again, will look in views folder for associated template
    end  
  end

  def edit
    @movie_to_edit = Movie.find(params[:id])
  end

  def update
    if @movie.update(movie_params)
      redirect_to movies_path
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :director, :release_year, :duration)
  end

  def load_movie
    @movie = Movie.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_movie
  before_filter :ensure_logged_in, only: [:create, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to movies_path, notice: 'Review created successfully'
    else
      render 'movies/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :movie_id)
  end

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_url
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to movies_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cast_members_helper.rb
module CastMembersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cast_members/create.html.erb
<h2>Add a Cast Member</h2>

<%= form_for ([@cast_member, @cast_member.name.build]) do |f| %>

<p>
  <%= f.label :name %> <br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :role %>
  <%= f.text_area :role %>
</p>
<p>
<%= f.submit %>
</p>
<% end -%>


<%= link_to 'Back', cast_member_path %>
<%= link_to 'Edit', edit_cast_member_path(@cast_member) %>

app/views/cast_members/destroy.html.erb
<h1>CastMembers#destroy</h1>
<p>Find me in app/views/cast_members/destroy.html.erb</p>

app/views/cast_members/show.html.erb
<p class="notice"></p>

<p>
  <strong>Content:</strong>
  <%= @cast_member.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @cast_member.user %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @cast_member.movie %>
</p>

<%= link_to 'Back', cast_member_path %>
<%= link_to 'Edit', edit_cast_member_path(@cast_member) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "Moviegur" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>

</head>

<body>

  <%= javascript_include_tag "application" %>

  <nav class="top-bar" data-topbar>
    <ul class="title-area">

      <li class="name">
        <h1><%= link_to 'Moviegur', '/' %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>
    
    <section class="top-bar-section">

      <ul class="right">
        <li class="divider"></li>

        <li><%= link_to 'New Movie', '/movies/new' %></li>
      </li>
      <li class="divider"></li>
      <li><a href="#">Main Item 2</a></li>
      <li class="divider"></li>

      <li><a href="#">Main Item 3</a></li>
    </li>
  </ul>
</section>
</nav>

<% if flash[:notice] %>
<p id="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
<p id="alert"><%= flash[:alert] %></p>
<% end %>



<%= yield %>

<p class="userinfo">
  <% if current_user %>
  Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
  <% else %>
  <p>   Already have an account? &raquo <%= link_to "Log in", new_session_path %> here or <%= link_to "Sign up", new_user_path %> </p>

  <% end %>
</p>







</body>
</html>

app/views/movies/_form.html.erb
<%= form_for (m) do |f| %>

  <% if m.errors.any? %>
    <div class="error_explanation">
      <p> <% m.errors.full_messages.each do |msg| %> 
        <%= msg %>,
      <% end -%>

      please try again!</p> 
    </div>
  <% end -%>

<%= f.label :title %>
<%= f.text_field :title %>  

<%= f.label :director %>
<%= f.text_field :director %> <br>

<%= f.label :release_year %>
<%= f.number_field :release_year %> <br>

<%= f.label :duration %>
<%= f.number_field :duration %> <br>

<%= f.submit %>

<% end -%>

app/views/movies/_movie.html.erb
<div class="row collapse">
    <div class="large-4 columns">
      <ul class="pricing-table left-side">
        <li class="price"><%= movie.title %></li>
        <li class="title"><%= movie.release_year %></li>
        
        <li class="bullet-item"><i class="foundicon-cloud"></i> Directed By: <%= movie.director %></li>
        <li class="bullet-item"><i class="foundicon-address-book"></i> Length: <%= movie.formatted_duration %></li>
        <li class="bullet-item"><i class="foundicon-address-book"></i> <%= link_to 'Show', movie %></li>
        <li class="bullet-item"><i class="foundicon-address-book"></i> <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?'} %></li>
      </ul>
    </div>
</div>

app/views/movies/edit.html.erb
<h1>Edit Your Moviegur Title</h1>

<%= render partial: "form", locals: { m: @movie_to_edit} %>


<%= link_to 'Show', @movie_to_edit %>
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Moviegur Magic</h1>

<ul>

  <%= render @movies %>
  
</ul>

app/views/movies/new.html.erb
<!-- <# if @movie.errors %>
  #show error messages
<# end -%> -->

<!-- form_for is writing out all the html form info -->

<h1>New Movie</h1>

<%= render partial: 'form', locals: { m: @movie } %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

  <p>Cast Members for <%= @movie.title %></p>

  <% @movie.cast_members.each do |cast_member| %>
    <p>
    Actor: <%= cast_member.name %> Charcter: <%= cast_member.role %>
    </p>
  <% end %>


<% if current_user %>
  <h3>Reviews</h3>

  <p>Reviews for <%= @movie.title %></p>

  <% @movie.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.email %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>



  <h4>New Review</h4>

  <%= form_for([@movie, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>


<% if current_user %>


  <h4>Add a New Cast Member</h4>

  <%= form_for([@movie, @cast_member]) do |f| %>
    <% if @cast_member.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@cast_member.errors.count, "error") %> prohibited this cast member from being saved:</h2>

        <ul>
        <% @cast_member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_area :name %>
    </div>
        <div class="field">
      <%= f.label :role %><br />
      <%= f.text_area :role %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a cast member.</p>
<% end %>

<h4><%= link_to "Delete Title", movie_path(@movie), method: :delete %></h4>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/reviews/create.html.erb
<h2>Add a Review</h2>

<%= form_for ([@review, @review.comment.build]) do |f| %>

<p>
  <%= f.label :commenter %> <br>
  <%= f.text_field :commenter %>
</p>

<p>
  <%= f.label :body %>
  <%= f.text_area :body %>

</p>
<p>
<%= f.submit %>
</p>
<% end -%>


<%= link_to 'Back', review_path %>
<%= link_to 'Edit', edit_review_path(@review) %>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<p class="notice"></p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @review.movie %>
</p>

<%= link_to 'Back', review_path %>
<%= link_to 'Edit', edit_review_path(@review) %>

app/views/users/new.html.erb
<div class="row">
    <div class="large-6 columns">
      <div class="signup-panel">
        <h1 class="welcome"> Sign Up For Moviegur!</h1>
        <%= form_for @user do |f| %>
          <% if @user.errors.any? %>
            <div class="error_messages">
              <h2>Form is invalid</h2>
              <ul>
                <% for message in @user.errors.full_messages %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="row collapse">
            <div class="small-10  columns">
              <%= f.label :email %><br/>
              <%= f.text_field :email %>
            </div>
          </div>
          <div class="row collapse">
            <div class="small-10 columns ">
              <%= f.label :password %><br/>
              <%= f.password_field :password %>
            </div>
          </div>
          <div class="row collapse">

            <div class="small-10  columns">
              <%= f.label :password_confirmation %><br/>
              <%= f.password_field :password_confirmation %>
            </div>
          </div>

        <div class="actions"><%= f.submit %></div>
        
      </div>
    </div>
   </div>    

   <% end %>          